# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Vijay Rengarajan
tagline:          'Ph.D. student, IIT Madras'
description:      'IIT Madras'
url:              http://apvijay.github.io/
baseurl:          /

author:
  name:           'Vijay Rengarajan'
  url:            http://apvijay.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/apvijay/apvijay.github.io
